# Generated by Django 3.0.7 on 2021-03-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Takip eyleminin gerçekleştiği tarih')),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='takip edilen')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='takip eden')),
            ],
            options={
                'verbose_name': 'Kullanıcı Takipçileri',
                'verbose_name_plural': 'Kullanıcı Takipçileri',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_imgs/defaultprofile.png', upload_to='profile_imgs/', verbose_name='Profil resmi')),
                ('bio', models.TextField(blank=True, max_length=350, verbose_name='Biyografi (bio)')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Konum')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profilli',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
